apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/d4depot/d4distributed-k3s-bootstrap.git
    targetRevision: HEAD
    chart: k3s-bootstrap
  syncPolicy: 
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
